import dotenv from 'dotenv';

import { ListenerType } from './listeners/ListenerType';

dotenv.config();

export const CONFIG = {
  /** SRV connection string for the MongoDB */
  MONGO_URL: process.env.MONGO_URL,
  /** URI where the RabbitMQ message broker is hosted */
  RABBITMQ_URL: process.env.RABBITMQ_URL,
  /** URI for heartbeat pings, via UptimeRobot for example */
  HEARTBEAT_URL: process.env.HEARTBEAT_URL as string,
  /** Settings for Moment */
  MOMENT: {
    /** Locale for the duration strings (i.e. 'één uur', 'tien minuten', 'twee dagen', etc.) generated by Moment */
    LOCALE: process.env.LOCALE || 'nl'
  },
  /** Language to use in the posts */
  LANG: process.env.LOCALE || 'nl',
  /** The port on which NOSEdits should listen for webhooks (Optional, default 7676) */
  PORT: process.env.PORT ? Number.parseInt(process.env.PORT as string) : 7676,
  /** Listener type, either 'webhook' or 'mq' for webhooks and amqp respectively. Make sure OpenTitles is configured with the same type of notifier. (Optional, default 'mq') */
  LISTENER: process.env.LISTENER || ListenerType.MessageQueue,
  /** Whether to use Twitter - true if all environment variables for Twitter are configured */
  USE_TWITTER: process.env.TWITTER_API_KEY && process.env.TWITTER_API_KEY_SECRET && process.env.TWITTER_ACCESS_TOKEN && process.env.TWITTER_ACCESS_TOKEN_SECRET,
  /** Whether to use Mastodon - true if all environment variables for Mastodon are configured */
  USE_MASTODON: process.env.MASTODON_ACCESS_TOKEN && process.env.MASTODON_API_URL,
  /** Whether to use BlueSky - true if all environment variables for BlueSky are configured */
  USE_BLUESKY: process.env.BLUESKY_IDENTIFIER && process.env.BLUESKY_PASSWORD,
  /** Variables for Twitter */
  TWITTER: {
    APP_KEY: process.env.TWITTER_API_KEY as string,
    APP_SECRET: process.env.TWITTER_API_KEY_SECRET as string,
    ACCESS_TOKEN: process.env.TWITTER_ACCESS_TOKEN as string,
    ACCESS_SECRET: process.env.TWITTER_ACCESS_TOKEN_SECRET as string
  },
  /** Variables for Mastodon */
  MASTODON: {
    /** Access token for the Mastodon account */
    ACCESS_TOKEN: process.env.MASTODON_ACCESS_TOKEN as string,
    /** API URL for the Mastodon instance, such as https://mastodon.social */
    API_URL: process.env.MASTODON_API_URL as string
  },
  /** Variables for BlueSky */
  BLUESKY: {
    /** Identifier for the BlueSky account - usually your email address */
    IDENTIFIER: process.env.BLUESKY_IDENTIFIER as string,
    /** Your BlueSky password, or app password for this account */
    PASSWORD: process.env.BLUESKY_PASSWORD as string
  }
}
