import { LOGLEVEL } from '@fdebijl/clog';
import { ListenerType } from './listeners/ListenerType';

export const CONFIG = {
  /** SRV connection string for the MongoDB */
  MONGO_URL: process.env.MONGO_URL,
  /** URI where the RabbitMQ broker is hosted */
  RABBITMQ_URL: process.env.RABBITMQ_URL,
  /** Locale for the duration strings (i.e. 'één uur', 'tien minuten', 'twee dagen', etc.) generated by Moment */
  MOMENT: {
    LOCALE: 'nl'
  },
  /** The port on which NOSEdits should listen for webhooks (Optional, default 7676) */
  PORT: process.env.PORT ? Number.parseInt(process.env.PORT as string) : 7676,
  /** Listener type, either 'webhook' or 'mq' for webhooks and amqp respectively. Make sure OpenTitles is configured with the same type of notifier. (Optional, default 'mq') */
  LISTENER: process.env.LISTENER || ListenerType.MessageQueue,
  /** Minimal log level for Clog (Optional, default LOGLEVEL.DEBUG) */
  MIN_LOGLEVEL: LOGLEVEL.DEBUG, //(process.env.MIN_LOGLEVEL as unknown as LOGLEVEL) ||
}