import dotenv from 'dotenv';

import { ListenerType } from './listeners/ListenerType';

dotenv.config();

export const CONFIG = {
  /** SRV connection string for the MongoDB */
  MONGO_URL: process.env.MONGO_URL,
  /** URI where the RabbitMQ message broker is hosted */
  RABBITMQ_URL: process.env.RABBITMQ_URL,
  /** URI for heartbeat pings, via UptimeRobot for example */
  HEARTBEAT_URL: process.env.HEARTBEAT_URL as string,
  /** Locale for the duration strings (i.e. 'één uur', 'tien minuten', 'twee dagen', etc.) generated by Moment */
  MOMENT: {
    LOCALE: 'nl'
  },
  /** The port on which NOSEdits should listen for webhooks (Optional, default 7676) */
  PORT: process.env.PORT ? Number.parseInt(process.env.PORT as string) : 7676,
  /** Listener type, either 'webhook' or 'mq' for webhooks and amqp respectively. Make sure OpenTitles is configured with the same type of notifier. (Optional, default 'mq') */
  LISTENER: process.env.LISTENER || ListenerType.MessageQueue,
  TWITTER: {
    APP_KEY: process.env.TWITTER_API_KEY as string,
    APP_SECRET: process.env.TWITTER_API_KEY_SECRET as string,
    ACCESS_TOKEN: process.env.TWITTER_ACCESS_TOKEN as string,
    ACCESS_SECRET: process.env.TWITTER_ACCESS_TOKEN_SECRET as string
  }
}
