name: Upload Codecov

on:
  push:
    branches:    
      - master

jobs:
  test:
    name: Test
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14
      - name: Start MongoDB
        uses: supercharge/mongodb-github-action@1.6.0
        with:
          mongodb-version: 4.2
      - name: Install dependencies
        run: npm ci
      - name: Run tests
        run: npm run test
        env:
          CI: true
          NODE_ENV: production