name: Upload Codecov

on:
  pull_request:
    branches:
      - master
      - main

env:
  NODE_VERSION: '18'

jobs:
  test:
    name: Test
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}
      - name: Start MongoDB
        uses: supercharge/mongodb-github-action@1.9.0
        with:
          mongodb-version: 4.2
      - name: Install dependencies
        run: npm ci
      - name: Run tests
        run: npm run test
        env:
          CI: true
          NODE_ENV: production
